#!/usr/bin/env python

from __future__ import print_function

import json
import os

print(json.dumps({
    'name': os.getenv('USER'),
    'uid': os.geteuid(),
    'gid': os.getgid(),
    'home': os.getenv('HOME'),
}, indent=2))
    
