---
install_packages:
  - vim
  - tmux
  - htop
  - git
  - lastpass-cli
  - powerline-fonts
  - libselinux-python
  - jq
  - python-virtualenv
  - python-pip
  - neovim
  - python3-neovim
  - python2-neovim
  - golang
  - composer
  - iftop
  - lua
  - lua-penlight
  - lua-posix

remove_packages:
  - PackageKit-command-not-found

flatpak_repos:
  - name: flathub
    url: https://flathub.org/repo/flathub.flatpakrepo

flatpak_packages:

  - name: com.slack.Slack
    repo: flathub

  - name: org.videolan.VLC
    repo: flathub

  - name: us.zoom.Zoom
    repo: flathub
