---
- name: set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: install rpmfusion-free yum repo
  become: true
  yum:
    name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: install rpmfusion-nonfree yum repo
  become: true
  yum:
    name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: install desired packages
  become: true
  dnf:
    name: '{{ install_packages}}'
    state: present

- name: remove undesired packages
  become: true
  dnf:
    name: '{{ remove_packages }}'
    state: absent

- include_tasks: custom-facts.yml
