---
- name: set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: install rpmfusion-free yum repo
  become: true
  yum:
    name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: install rpmfusion-nonfree yum repo
  become: true
  yum:
    name: http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

- name: install desired packages
  become: true
  dnf:
    name: '{{ pkg }}'
    state: present
  with_items:
    - '{{ install_packages }}'
  loop_control:
    loop_var: pkg

- name: remove undesired packages
  become: true
  dnf:
    name: '{{ pkg }}'
    state: absent
  with_items:
    - '{{ remove_packages }}'
  loop_control:
    loop_var: pkg

- include_tasks: custom-facts.yml
